baseurl: ""
exclude: [
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'Makefile',
  'README.md',
]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tex

sass:
  sass_dir: _scss
  style: :compressed

# --- Jekyll SEO ---
title: Yan Ke
description: >-
  Hi! I'm Yan Ke and I am currently a student at the University of Waterloo
  studying Computer Science. Check out what I'm up to on my blog or what
  I'm working on. :)

url: https://itsyan.me
logo: /assets/img/dp.png

author: yan
google_site_verification: 3qoNBH9p7R2jfzU-xH2aNq0fLwm6lXVyJgMw-_Wu6OY

# --- Jekyll Tex ---
tex:
  source: _tex
  output: assets
