baseurl: ""
exclude: [
  'node_modules',
  'vendor',
  'script',
  'webpack',
  'webpack.config.js',
  'package.json',
  'package-lock.json',
  'Gemfile',
  'Gemfile.lock',
  'README.md'
]

markdown: kramdown
plugins:
  - jekyll-compress-images
  - jekyll-seo-tag
  - jekyll-sitemap

compress_images:
  images_path: "assets/img/**/*.{gif,png,jpg,jpeg,svg}"

sass:
  sass_dir: _scss
  style: :compressed

collections:
  projects:
    output: true

# --- Jekyll SEO ---
title: Yan Ke
description: >-
  Hi! I'm Yan Ke and I am currently a student at the University of Waterloo studying Computer Science. Check out what I'm up to on my blog or what I'm working on. :)

url: https://itsyan.me
logo: /assets/img/dp.png

author: yan
google_site_verification: 3qoNBH9p7R2jfzU-xH2aNq0fLwm6lXVyJgMw-_Wu6OY

social:
  name: Yan Ke
  links:
    - https://github.com/yanske1
    - https://www.facebook.com/yansongke
    - https://www.linkedin.com/in/yanske1/
