title: Yan Ke Personal Website
description: >-
  Yan Ke UW University of Waterloo CS Software Engineering Student Intern Personal
  Website Blog Projects Work

baseurl: ""
url: ""

markdown: kramdown
plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _scss
  style: :compressed

collections:
  projects:
    output: true
