#!/bin/bash

function showUsage() {
  echo "Usage: { project | post } \"Title of My New Post\""
}

function showExists() {
  echo "File already exists with name $1"
}

function showCreated() {
  GREEN='\033[0;32m'
  NC='\033[0m'
  echo -e "${GREEN}Created${NC} $1"
}

function createPost() {
  date=$(date +%Y-%m-%d)
  slugged=$(echo $1 | sed -e 's/ /-/g')
  filePath="_posts/$date-$slugged.md"

  if [ -e $filePath ] ; then
    showExists $filePath
    exit 1
  fi

  mkdir -p "_posts"
  touch $filePath

  headerDate=$(date "+%B %d, %Y")

  # Populate template
  echo "---" >> $filePath
  echo "layout: post" >> $filePath
  echo "title: $1" >> $filePath
  echo "date: $headerDate" >> $filePath
  echo "---" >> $filePath
  echo >> $filePath
  echo "Content ..." >> $filePath

  showCreated $filePath
}

function createProject() {
  date=$(date +%Y-%m-%d)
  slugged=$(echo $1 | sed -e 's/./\L&/g' -e 's/ /_/g')
  filePath="_projects/$slugged.md"

  if [ -e $filePath ] ; then
    showExists $filePath
    exit 1
  fi

  mkdir -p "_projects"
  touch $filePath

  # Populate template
  echo "---" >> $filePath
  echo "layout: project" >> $filePath
  echo "title: $1" >> $filePath
  echo "tools: " >> $filePath
  echo "date: $date" >> $filePath
  echo "dp: projectImage.png" >> $filePath
  echo "img: projectImage.png" >> $filePath
  echo "desc: Short description here" >> $filePath
  echo "---" >> $filePath
  echo >> $filePath
  echo "Content ..." >> $filePath

  showCreated $filePath
}

# Validate two params are passed in
if [ $# != 2 ] ; then
  showUsage
  exit 1;
fi

if [ $1 == "project" ] ; then
  createProject "$2"
elif [ $1 == "post" ] ; then
  createPost "$2"
else
  showUsage
  exit 1;
fi
